Repository Dacoband/SWP391-Artix, pull requests merged in 2024-04, with the labels that each got.

#114 Volka Add big FIle
  backend/backend/Controllers/AccountController.cs
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/Controllers/CommentsController.cs
  backend/backend/Controllers/CommissionController.cs
  backend/backend/Controllers/CommissionFormController.cs
  backend/backend/Controllers/CreatorController.cs
  backend/backend/Controllers/VnpayPaymentController.cs
  backend/backend/Entities/MailRequest.cs
  backend/backend/Entities/WelcomeRequest.cs
  backend/backend/backend.csproj
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.assets.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.CoreCompileInputs.cache
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
  backend/backend/obj/backend.csproj.nuget.dgspec.json
  backend/backend/obj/project.assets.json
  backend/backend/obj/project.nuget.cache
Labels: documentation, duplicate, enhancement, Create, Fix-Code

#115 Thucvip
  backend/backend/Controllers/FollowsController.cs
  backend/backend/Controllers/OrderDetailController.cs
  backend/backend/Controllers/PaymentController.cs
  backend/backend/Controllers/UserInfo.cs
  backend/backend/Entities/ArtworkTag.cs
  backend/backend/Entities/ArtworkViewModel.cs
  backend/backend/Entities/Artworks.cs
  backend/backend/Entities/ArtworksResponse.cs
  backend/backend/Entities/CommissionForm.cs
  backend/backend/Entities/Creator.cs
  backend/backend/Entities/EmailModel.cs
  backend/backend/Entities/OrderDetail.cs
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.GeneratedMSBuildEditorConfig.editorconfig
  backend/backend/obj/Debug/net8.0/backend.assets.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.CoreCompileInputs.cache
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
  backend/backend/obj/backend.csproj.nuget.dgspec.json
  backend/backend/obj/backend.csproj.nuget.g.props
  backend/backend/obj/project.assets.json
  backend/backend/obj/project.nuget.cache
Labels: documentation, enhancement, Create, Fix-Code

#116 Update code and Folder
  backend/backend/Entities/DTO/PaymentResponseModel.cs
  backend/backend/Entities/DTO/VnPayLibrary.cs
  backend/backend/appsettings.json
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
Labels: documentation, enhancement, Create

#117 Volka add new code
  backend/backend/Controllers/VnpayPaymentController.cs
  backend/backend/Service/IMailService.cs
  backend/backend/Service/IVnPayService.cs
  backend/backend/Service/MailService.cs
  backend/backend/Service/VnPayService.cs
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.CoreCompileInputs.cache
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
Labels: documentation, enhancement, Fix-Code
