Repository Dacoband/SWP391-Artix, pull requests merged in 2024-02, with the labels that each got.

#27 Big Update
  Database/Artix.sql
  Database/ArtixData.md
  Database/SWP391-G4.pdf
  Database/SWP391-G4.svg
  backend/backend/Controllers/CreatorController.cs
  backend/backend/Data/DbContext.cs
  backend/backend/Entities/Account.cs
  backend/backend/Entities/Artwork.cs
  backend/backend/Entities/Comments.cs
  backend/backend/Entities/Commission.cs
  backend/backend/Entities/CommissionForm.cs
  backend/backend/Entities/Creator.cs
  backend/backend/Entities/Follow.cs
  backend/backend/Entities/Moderators.cs
  backend/backend/Entities/Notification.cs
  backend/backend/Entities/Order.cs
  backend/backend/Entities/OrderDetail.cs
  backend/backend/Entities/PaypalAccount.cs
  backend/backend/Entities/Report.cs
  backend/backend/Entities/Roles.cs
  backend/backend/Entities/Tags.cs
  backend/backend/Entities/ViewReport.cs
  backend/backend/backend.csproj
Labels: documentation, good first issue, Create

#30 Add Attribute for Object
  Database/ArtixData.md
  backend/backend/Entities/Account.cs
  backend/backend/Entities/Artwork.cs
  backend/backend/Entities/Artworks.cs
  backend/backend/Entities/Comments.cs
  backend/backend/Entities/Commission.cs
  backend/backend/Entities/CommissionForm.cs
  backend/backend/Entities/Creator.cs
  backend/backend/Entities/Follow.cs
  backend/backend/Entities/Moderators.cs
  backend/backend/Entities/Notification.cs
  backend/backend/Entities/Order.cs
  backend/backend/Entities/OrderDetail.cs
  backend/backend/Entities/PaypalAccount.cs
  backend/backend/Entities/Report.cs
  backend/backend/Entities/Roles.cs
  backend/backend/Entities/Tags.cs
  backend/backend/Entities/ViewReport.cs
Labels: documentation, enhancement, Create

#38 Delete DataContext.cs
  backend/backend/Data/DataContext.cs
Labels: bug

#39 Big Add Controller
  Database/Artix.sql
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/Controllers/CommentsController.cs
  backend/backend/Controllers/CommissionController.cs
  backend/backend/Controllers/CommissionFormController.cs
  backend/backend/Controllers/CreatorController.cs
  backend/backend/Controllers/FollowsController.cs
  backend/backend/Controllers/OrdersController.cs
  backend/backend/Controllers/ReportsController.cs
  backend/backend/Controllers/TagController.cs
  backend/backend/Controllers/ViewReportController.cs
  backend/backend/Data/DataContext.cs
  backend/backend/backend - Backup.csproj
  backend/backend/backend.csproj
Labels: documentation, enhancement, good first issue, Create

#42 Volka
  backend/backend/Controllers/ModeratorsController.cs
  backend/backend/Controllers/NotificationController.cs
  backend/backend/Controllers/OrderDetailController.cs
  backend/backend/Controllers/PayPalAccountController.cs
  backend/backend/Controllers/RoleController.cs
  backend/backend/backend - Backup (1).csproj
  backend/backend/backend.csproj
Labels: Fix-Code

#43 AppJSONSetting
  backend/backend/Controllers/CommentsController.cs
  backend/backend/Data/DataContext.cs
  backend/backend/appsettings.json
Labels: documentation, enhancement, help wanted, Create, Fix-Code

#51 Merge code
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/Controllers/CommissionFormController.cs
  backend/backend/Data/DataContext.cs
  backend/backend/Program.cs
Labels: documentation, enhancement, Fix-Code

#53 Merge code
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/Controllers/CommentsController.cs
  backend/backend/Controllers/CommissionController.cs
  backend/backend/Controllers/CommissionFormController.cs
  backend/backend/Controllers/CreatorController.cs
  backend/backend/Controllers/FollowsController.cs
  backend/backend/Controllers/ModeratorsController.cs
  backend/backend/Controllers/NotificationController.cs
  backend/backend/Controllers/OrderDetailController.cs
  backend/backend/Controllers/OrdersController.cs
  backend/backend/Controllers/PayPalAccountController.cs
  backend/backend/Controllers/ReportsController.cs
  backend/backend/Controllers/RoleController.cs
  backend/backend/Controllers/TagController.cs
  backend/backend/Controllers/ViewReportController.cs
  backend/backend/Data/DataContext.cs
Labels: Fix-Code

#61 fix code
  backend/backend/Entities/CommissionForm.cs
  backend/backend/Entities/Notification.cs
  backend/backend/Entities/OrderDetail.cs
  backend/backend/Entities/ViewReport.cs
  backend/backend/appsettings.json
  backend/backend/bin/Debug/net8.0/appsettings.json
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
Labels: documentation, enhancement, Fix-Code

#63 Pull Fix
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/backend.csproj
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.GeneratedMSBuildEditorConfig.editorconfig
  backend/backend/obj/Debug/net8.0/backend.assets.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.CoreCompileInputs.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.FileListAbsolute.txt
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.genruntimeconfig.cache
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
  backend/backend/obj/backend.csproj.nuget.dgspec.json
  backend/backend/obj/backend.csproj.nuget.g.props
  backend/backend/obj/project.assets.json
  backend/backend/obj/project.nuget.cache
Labels: documentation, enhancement, Fix-Code

#64 Volka
  backend/backend/Controllers/FollowsController.cs
  backend/backend/Entities/Follow.cs
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.GeneratedMSBuildEditorConfig.editorconfig
  backend/backend/obj/Debug/net8.0/backend.assets.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.CoreCompileInputs.cache
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.genruntimeconfig.cache
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
  backend/backend/obj/backend.csproj.nuget.dgspec.json
  backend/backend/obj/backend.csproj.nuget.g.props
  backend/backend/obj/project.assets.json
  backend/backend/obj/project.nuget.cache
Labels: enhancement, Fix-Code

#65 Volka
  backend/backend/Controllers/ArtworksController.cs
  backend/backend/Controllers/CommentsController.cs
  backend/backend/Controllers/CommissionController.cs
  backend/backend/Controllers/CommissionFormController.cs
  backend/backend/Controllers/CreatorController.cs
  backend/backend/Controllers/FollowsController.cs
  backend/backend/Controllers/ModeratorsController.cs
  backend/backend/Controllers/NotificationController.cs
  backend/backend/Controllers/OrderDetailController.cs
  backend/backend/Controllers/OrdersController.cs
  backend/backend/Controllers/PayPalAccountController.cs
  backend/backend/Controllers/ReportsController.cs
  backend/backend/Controllers/RoleController.cs
  backend/backend/Controllers/TagController.cs
  backend/backend/Controllers/ViewReportController.cs
  backend/backend/Data/DataContext.cs
  backend/backend/Entities/CommissionForm.cs
  backend/backend/Entities/Creator.cs
  backend/backend/Entities/Follow.cs
  backend/backend/Entities/Notification.cs
  backend/backend/Entities/OrderDetail.cs
  backend/backend/Entities/ViewReport.cs
  backend/backend/Program.cs
  backend/backend/appsettings.json
  backend/backend/backend.csproj
  backend/backend/bin/Debug/net8.0/Swashbuckle.AspNetCore.Swagger.dll
  backend/backend/bin/Debug/net8.0/Swashbuckle.AspNetCore.SwaggerGen.dll
  backend/backend/bin/Debug/net8.0/Swashbuckle.AspNetCore.SwaggerUI.dll
  backend/backend/bin/Debug/net8.0/appsettings.json
  backend/backend/bin/Debug/net8.0/backend.deps.json
  backend/backend/bin/Debug/net8.0/backend.dll
  backend/backend/bin/Debug/net8.0/backend.pdb
  backend/backend/bin/Debug/net8.0/backend.runtimeconfig.json
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfo.cs
  backend/backend/obj/Debug/net8.0/backend.AssemblyInfoInputs.cache
  backend/backend/obj/Debug/net8.0/backend.csproj.FileListAbsolute.txt
  backend/backend/obj/Debug/net8.0/backend.dll
  backend/backend/obj/Debug/net8.0/backend.genruntimeconfig.cache
  backend/backend/obj/Debug/net8.0/backend.pdb
  backend/backend/obj/Debug/net8.0/ref/backend.dll
  backend/backend/obj/Debug/net8.0/refint/backend.dll
  backend/backend/obj/Debug/net8.0/staticwebassets/msbuild.buildMultiTargeting.backend.props
  backend/backend/obj/Debug/net8.0/staticwebassets/msbuild.buildTransitive.backend.props
Labels: documentation, enhancement, Fix-Code
